### ISSUE TITLE
NOIP2018颓废之路 | yltx's blog

### ISSUE THREAD

**Issue by yltx** [yltx/yltx.github.io#103]
https://yltx.cf/2019/01/12/NOIP2018%E9%A2%93%E5%BA%9F%E4%B9%8B%E8%B7%AF/ 

 初赛上午颓了一上午有题。然后，什么资料没看，装作都懂的样子。 下午进考点，与一个同学一起挤到前面，身后一群27中的占领了整条路。。。这就是搞OI和不搞OI的学校的区别吧。。。 进考场，我很淡定的答题，完了4：00就写完了。于是检查结果改错了一道8分的题，听说不给带试卷，于是机智的我将答案抄到了我的课表上算不算作弊啊，出考场，对答案，还好，75，应该能过了。 晚上上洛谷颓，结果被3个巨佬吊打，果断走

**Comment by yltx** [comment]
。

**Comment by R-G-Mocoratioen** [comment]
tql！
