### ISSUE TITLE
某谷讲师语录 | yltx's blog

### ISSUE THREAD

**Issue by yltx** [yltx/yltx.github.io#104]
https://yltx.cf/2019/07/16/%E6%9F%90%E8%B0%B7%E8%AE%B2%E5%B8%88%E8%AF%AD%E5%BD%95/#more 

 RT. zzy(Created_equal1) 我*  太有毒了  那我就当是我说的了  你会发现这个a[2]特别牛*  麻将个锤子  怎么“lòng”  你们一说上过了我就好慌  先容我喝一口水  怎么又要推笔记啊  我学艺不精  三分钟很长  粗鄙之语，不足于耳啊  我来在线丢人了  我跟楼叉楼很熟的  我有毒  有点丢人  给我幼小的心灵沉重的打击  我也觉得不要对CCF抱太大期望   Sc

**Comment by FruitCandysjf** [comment]
前排吃瓜（zzy语录和Scarlet语录是我做的！qwq）

**Comment by yltx** [comment]
> @FruitCandysjf
> 前排吃瓜（zzy语录和Scarlet语录是我做的！qwq）

OrzN_D巨佬

**Comment by Flamire** [comment]
ND是神仙orz

**Comment by yltx** [comment]
> @Flamire
> ND是神仙orz

说的就像您不是神仙一样

**Comment by FruitCandysjf** [comment]
> @Flamire
> ND是神仙orz

Flamire是神仙orz
