### ISSUE TITLE
睡前读物：我为何而OI | yltx's blog

### ISSUE THREAD

**Issue by yltx** [yltx/yltx.github.io#105]
https://yltx.cf/2019/08/03/%E7%9D%A1%E5%89%8D%E8%AF%BB%E7%89%A9%EF%BC%9A%E6%88%91%E4%B8%BA%E4%BD%95%E8%80%8COI/#more 

 为了获得最佳的阅读体验，请在睡前阅读 有时候，我会莫名思考一些事情，于是有了这篇口胡的文章。 前言我为何而OI？ 我不清楚。 但我知道，我搞OI 我也应该去搞OI 哪怕没有别人的帮助 哪怕一个人孤独 我 注定OI OI黑历史为了您的阅读体验，本部分使用上帝视角。 四年级/2014四年级那个暑假，我爸问我：  你喜欢电脑吗？喜欢。那你叫你妈带你去市里报名。哦。  五年级/2015六年级/2016初一

**Comment by yltx** [comment]
想知道把这篇文章看完没睡着的人是什么感受QAQ

**Comment by FruitCandysjf** [comment]
希望yltx能够尽早回归qwq  
yjy AK CSP !

**Comment by yltx** [comment]
> @FruitCandysjf
> 希望yltx能够尽早回归qwq  
> yjy AK CSP !

谢谢……不过AK CSP是不存在的

**Comment by tiger0132** [comment]
Orz
我可能是真的因为兴趣才搞 OI 的吧……
但是还是这么菜 >_<

**Comment by yltx** [comment]
> @tiger0132
> Orz
> 我可能是真的因为兴趣才搞 OI 的吧……
> 但是还是这么菜 >_<

Orz，不过您就不要fAKe了

**Comment by code004Accepted** [comment]
为何我初二也是被家长威胁停OI搞文化课？

为何我初二期末也是rk3？

@yltx  .........................

**Comment by yltx** [comment]
> @code004Accepted
> 为何我初二也是被家长威胁停OI搞文化课？
> 
> 为何我初二期末也是rk3？
> 
> @yltx  .........................
23333不过您肯定比我强

**Comment by code004Accepted** [comment]
不可能 我就是个蓝名小蒟蒻...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"引领天下"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月8日(星期天) 晚上8:34
收件人:&nbsp;"yltx/yltx.github.io"<yltx.github.io@noreply.github.com&gt;;
抄送:&nbsp;"code004"<code004@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yltx/yltx.github.io] 睡前读物：我为何而OI | yltx's blog (#105)



 
@code004Accepted
 为何我初二也是被家长威胁停OI搞文化课？
 
为何我初二期末也是rk3？
 
@yltx  .........................
 23333不过您肯定比我强
